#!/bin/sh
# $FreeBSD$
#
############################################################ INCLUDES

BSDCFG_SHARE="/usr/share/bsdconfig"
. $BSDCFG_SHARE/common.subr || exit 1
f_dprintf "%s: loading includes..." "$0"
f_include $BSDCFG_SHARE/dialog.subr

############################################################ MAIN

: ${BSDDIALOG_OK=0}
: ${BSDDIALOG_CANCEL=1}

INTERFACE=$1
IFCONFIG_PREFIX="$2"
test -z "$IFCONFIG_PREFIX" || IFCONFIG_PREFIX="$2 "
case "${INTERFACE}" in
"")	bsddialog --backtitle "XLOG Firewall" --title 'Network Yapılandırması' \
	    --msgbox 'No interface specified for IPv4 configuration.' 0 0
	exit 1
	;;
esac

bsddialog --backtitle "XLOG Firewall" --title 'Network Yapılandırması' --yesno 'Bu arabirimi DHCP olarak yapılandırmak ister misiniz?' 0 0
if [ $? -eq $BSDDIALOG_OK ]; then
		# XXX: get interface down otherwise after installation restart
		# dhclient does not build a new resolv.conf (see PR262262).
		ifconfig $INTERFACE down
		ifconfig $INTERFACE up
		bsddialog --backtitle "XLOG Firewall" --infobox " DHCP lease alınıyor..." 0 0
		err=$( pkill -F /var/run/dhclient/dhclient.${INTERFACE}.pid > /dev/null 2>&1; ifconfig ${INTERFACE} -alias; dhclient $INTERFACE 2>&1 )
		echo "burak"
		echo $err
		if [ $? -ne 0 ]; then
			f_dprintf "%s" "$err"
			bsddialog --backtitle "XLOG Firewall" --msgbox "DHCP lease acquisition failed." 0 0
			exec $0 ${INTERFACE} "${IFCONFIG_PREFIX}"
		fi
	echo ifconfig_$INTERFACE=\"${IFCONFIG_PREFIX}DHCP\" >> /etc/rc.conf
	exit 0
fi

IP_ADDRESS=`ifconfig $INTERFACE inet | awk '/inet/ {printf("%s\n", $2); }'`
#NETMASK=`ifconfig $INTERFACE inet | awk '/inet/ {printf("%s\n", $4); }'`
#ROUTER=`netstat -rn -f inet | awk '/default/ {printf("%s\n", $2);}'`

exec 3>&1
IF_CONFIG=$(bsddialog --backtitle "XLOG Firewall" --title 'Network Yapılandırması' --form 'Statik IP Yapılandırması' 0 0 0 \
	'IP Address' 1 1 "$IP_ADDRESS" 1 20 16 0 \
	'Subnet Mask' 2 1 "$NETMASK" 2 20 16 0 \
	'Default Router' 3 1 "$ROUTER" 3 20 16 0 \
2>&1 1>&3)
if [ $? -eq $BSDDIALOG_CANCEL ]; then exit 1; fi
exec 3>&-

echo $INTERFACE $IF_CONFIG |
    awk -v prefix="$IFCONFIG_PREFIX" '{
	printf("ifconfig_%s=\"%s\inet %s netmask %s\"\n", $1, prefix, $2, $3);
	printf("defaultrouter=\"%s\"\n", $4);
    }' >> /etc/rc.conf
	ifconfig $INTERFACE $IP_ADDRESS netmask $NETMASK > /dev/null 2>&1
retval=$?

defrouter=0
if [ $defrouter ]; then
	. /etc/rc.conf
	if [ -n "$2" ]; then
		ifconfig $INTERFACE `eval echo \\\$ifconfig_$INTERFACE | sed "s|$2||"`
	else
		ifconfig $INTERFACE `eval echo \\\$ifconfig_$INTERFACE`
	fi
	if [ "$defaultrouter" ]; then
		#route delete -inet default > /dev/null 2>&1
		#route add -inet default $defaultrouter > /dev/null 2>&1
		retval=$?
	fi
fi

exit $retval

################################################################################
# END
################################################################################
